//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInformation.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstState
    {
        public tblMstState()
        {
            this.tblMstCities = new HashSet<tblMstCity>();
            this.tblUserInfoes = new HashSet<tblUserInfo>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<tblMstCity> tblMstCities { get; set; }
        public virtual tblMstCountry tblMstCountry { get; set; }
        public virtual ICollection<tblUserInfo> tblUserInfoes { get; set; }
    }
}
